import type { PromptDoc } from "../types";

// Daily prompt bank — no timer (timeLimitSeconds: null). Combined with
// timeSensitive.ts in seed.ts to form the full prompt bank written to
// /prompts. Hand-edit this list to add/tweak daily prompts; ids must
// stay stable and unique since they're used as Firestore doc ids.
export const DAILY_PROMPTS: (PromptDoc & { id: string })[] = [
  { id: "daily_01", promptText: "Today, keep your eyes peeled for green. Snap anything that catches your eye.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_02", promptText: "Find your favourite colour hiding somewhere around you.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_03", promptText: "Can you spot three different shades of the same colour?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_04", promptText: "Find a colour combination you wouldn't normally notice.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_05", promptText: "Snap something unexpectedly colourful.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_06", promptText: "Blue is today's colour. But skip the sky!", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_07", promptText: "Keep an eye out for something yellow hiding in plain sight.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_08", promptText: "Snap something with at least three different colours.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_09", promptText: "Find the most colourful thing you see today.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_10", promptText: "Look for a tiny pop of colour in an otherwise boring scene.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_11", promptText: "Today, capture something you find beautiful.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_12", promptText: "Snap something you normally walk straight past.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_13", promptText: "Find a little bit of beauty in something ordinary.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_14", promptText: "What's your favourite thing you see today? Snap it.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_15", promptText: "Capture something that makes you smile.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_16", promptText: "Find something that looks better than it should.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_17", promptText: "Today, look for a moment that feels peaceful.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_18", promptText: "Snap something you think deserves more attention.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_19", promptText: "Find something beautiful in an unexpected place.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_20", promptText: "Look closely. Capture a tiny detail you might normally miss.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_21", promptText: "Keep an eye out for something perfectly symmetrical.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_22", promptText: "Can you spot a circle in the wild?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_23", promptText: "Today, hunt down a triangle.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_24", promptText: "Capture the most interesting pattern you see.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_25", promptText: "Look around. Can you spot repeating shapes?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_26", promptText: "Find something with interesting lines.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_27", promptText: "Spot two things that accidentally match.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_28", promptText: "Find something that looks like a letter.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_29", promptText: "Nature has some pretty cool patterns. Find one.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_30", promptText: "Get close. Capture something with an interesting texture.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_31", promptText: "See the world differently today. Photograph something from an unusual angle.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_32", promptText: "Look up! What's worth capturing above you?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_33", promptText: "Look down! What have you been missing?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_34", promptText: "Get closer than usual. Capture a tiny detail.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_35", promptText: "Find something that looks completely different from far away.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_36", promptText: "Can you capture something through another object?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_37", promptText: "Keep an eye out for an interesting reflection.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_38", promptText: "Today, chase the shadows.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_39", promptText: "Get low. Capture something from ground level.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_40", promptText: "Can you photograph something without showing it directly?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_41", promptText: "Capture something happening around you.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_42", promptText: "Snap a moment you wish you could keep forever.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_43", promptText: "Find something that tells a story without saying a word.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_44", promptText: "Capture a tiny moment from everyday life.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_45", promptText: "Find something that feels nostalgic.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_46", promptText: "What reminds you of being a kid? Snap it.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_47", promptText: "Keep your eyes open for something unexpectedly funny.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_48", promptText: "Capture something that makes today feel like today.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_49", promptText: "Look for a little moment of connection.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_50", promptText: "Snap something you think you'll remember later.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_51", promptText: "Find the weirdest thing you see today.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_52", promptText: "Can you spot something that looks like a face?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_53", promptText: "Find something that definitely shouldn't be where it is.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_54", promptText: "What's the most interesting thing within reach?", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_55", promptText: "Find something that makes you think, \"Why is that there?\"", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_56", promptText: "Spot something that looks like something completely different.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_57", promptText: "Pick your favourite object around you. Don't touch it — just snap it.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_58", promptText: "Find something tiny hiding somewhere.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_59", promptText: "Spot something completely out of place.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
  { id: "daily_60", promptText: "Photograph something you'd normally never think to photograph.", type: "daily", timeLimitSeconds: null, difficulty: "medium", tags: [] },
];
